### ISSUE TITLE
D2.2 Technology Evaluation, Containerization and Optimization Strategy: draft ready 08.10.21 - due M10

### ISSUE THREAD

**Issue by petrova-elsayed** [eflows4hpc/WP2-Action-Items#13]
- Lead **BULL**
- Review **UPV**

**Comment by petrova-elsayed** [comment]
Lead BULL
Review DtoK

**Comment by jrybicki-jsc** [comment]
Based on the available requirements, this deliverable will derive a strategy for optimizing deployment in all envisioned dimensions: by optimizing libraries and runtimes, using containers, and application of emerging storage solutions. Tasks 2.1, 2.2, 2.3 contribute to this deliverable.
